### PR TITLE
rename "deps" -> "_" when unused

### PR DESCRIPTION
**Pull request by yuval-klotho**
Just more cleanup.

### Standard checks

- **Unit tests**: n/a
- **Docs**: n/a
- **Backwards compatibility**: no issues

### CODE REVIEW

**Review by gordon-klotho — APPROVED** [review]
I wouldn't (and obviously didn't) use `_` for function parameters, but I'm not opposed to the change.

**Comment by yuval-klotho** [comment]
> I wouldn't (and obviously didn't) use `_` for function parameters, but I'm not opposed to the change.

Intellij warns about them. Should I just turn off that warning?

**Comment by gordon-klotho** [comment]
Is there a way to configure Intellij to use golangci-lint? That way it stays in sync with the git hook / check as well.

In VSCode this is in
image

**Comment by yuval-klotho** [comment]
Will withdraw this, and use [FileWatchers](https://www.jetbrains.com/help/go/settings-tools-file-watchers.html) instead.

**Pull request closed without merging**
